'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type ExampleInputCustomEvent } from "@example/stencil-lib";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@example/stencil-lib-react";
import type { Components } from "@example/stencil-lib/dist/components";
import { ExampleCard as ExampleCardElement } from "@example/stencil-lib/dist/components/example-card.js";
import { ExampleInput as ExampleInputElement } from "@example/stencil-lib/dist/components/example-input.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "default": "declarative-shadow-dom" };

export type ExampleCardEvents = NonNullable<unknown>;

export const ExampleCard: StencilReactComponent<ExampleCardElement, ExampleCardEvents, Components.ExampleCard> = /*@__PURE__*/ createComponent<ExampleCardElement, ExampleCardEvents, Components.ExampleCard>({
    tagName: 'example-card',
    properties: {},
    hydrateModule: typeof window === 'undefined' ? (import('@example/stencil-lib/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.ExampleCard as StencilReactComponent<ExampleCardElement, ExampleCardEvents, Components.ExampleCard>,
    serializeShadowRoot
});

export type ExampleInputEvents = {
    onExampleChange: EventName<ExampleInputCustomEvent<string>>,
    onExampleFocus: EventName<ExampleInputCustomEvent<void>>,
    onExampleBlur: EventName<ExampleInputCustomEvent<void>>
};

export const ExampleInput: StencilReactComponent<ExampleInputElement, ExampleInputEvents, Components.ExampleInput> = /*@__PURE__*/ createComponent<ExampleInputElement, ExampleInputEvents, Components.ExampleInput>({
    tagName: 'example-input',
    properties: {
        value: 'value',
        placeholder: 'placeholder',
        disabled: 'disabled'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@example/stencil-lib/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.ExampleInput as StencilReactComponent<ExampleInputElement, ExampleInputEvents, Components.ExampleInput>,
    serializeShadowRoot
});
