'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type ExampleInputCustomEvent } from "@example/stencil-lib";
import type { Components } from "@example/stencil-lib/dist/components";
import { ExampleCard as ExampleCardElement, defineCustomElement as defineExampleCard } from "@example/stencil-lib/dist/components/example-card.js";
import { ExampleInput as ExampleInputElement, defineCustomElement as defineExampleInput } from "@example/stencil-lib/dist/components/example-input.js";

export type ExampleCardEvents = NonNullable<unknown>;

export const ExampleCard: StencilReactComponent<ExampleCardElement, ExampleCardEvents, Components.ExampleCard> = /*@__PURE__*/ createComponent<ExampleCardElement, ExampleCardEvents, Components.ExampleCard>({
    tagName: 'example-card',
    elementClass: ExampleCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ExampleCardEvents,
    defineCustomElement: defineExampleCard
});

export type ExampleInputEvents = {
    onExampleChange: EventName<ExampleInputCustomEvent<string>>,
    onExampleFocus: EventName<ExampleInputCustomEvent<void>>,
    onExampleBlur: EventName<ExampleInputCustomEvent<void>>
};

export const ExampleInput: StencilReactComponent<ExampleInputElement, ExampleInputEvents, Components.ExampleInput> = /*@__PURE__*/ createComponent<ExampleInputElement, ExampleInputEvents, Components.ExampleInput>({
    tagName: 'example-input',
    elementClass: ExampleInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onExampleChange: 'exampleChange',
        onExampleFocus: 'exampleFocus',
        onExampleBlur: 'exampleBlur'
    } as ExampleInputEvents,
    defineCustomElement: defineExampleInput
});
